# Generated by Django 4.2 on 2023-04-11 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patronymic_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="patronymic"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="birthday")),
                ("sex", models.CharField(max_length=1, verbose_name="user sex")),
                (
                    "edited_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date edited"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
