# Generated by Django 4.2 on 2023-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateTimeField(verbose_name="Дата рождения"),
        ),
    ]
