# Generated by Django 4.2 on 2023-04-30 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 30, 8, 36, 7, 728716, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата рождения",
            ),
        ),
    ]
