# Generated by Django 4.2 on 2023-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateTimeField(verbose_name="Дата рождения"),
        ),
    ]
