# Generated by Django 4.2 on 2023-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
