# Generated by Django 4.2 on 2023-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="online_status",
            field=models.CharField(
                choices=[
                    ("Online", "В сети"),
                    ("Offline", "Не в сети"),
                    ("In Game", "В игре"),
                ],
                default="Offline",
                max_length=7,
                verbose_name="Статус",
            ),
        ),
    ]
