# Generated by Django 4.2 on 2023-04-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_timing",
            field=models.CharField(
                default="00:00", max_length=5, verbose_name="Продолжительность игры"
            ),
        ),
    ]
