# Generated by Django 4.2 on 2023-04-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_game_timing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game", old_name="edited_date", new_name="date",
        ),
    ]
