# Generated by Django 4.2 on 2023-04-29 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0003_rename_edited_date_game_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player1",
            field=models.ForeignKey(
                on_delete=models.SET(2),
                related_name="player1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player2",
            field=models.ForeignKey(
                on_delete=models.SET(2),
                related_name="player2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
